name: Continuous Integration

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
      - name: Run tests
        run: |
          rails db:migrate RAILS_ENV=test
          bundle exec rspec
